# Generated by Django 4.2.17 on 2025-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='alternate_no',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='cimcon_part_no',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='mfg_part_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='cimcon_part_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='itemCode',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='make',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='makeCode',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='mfgPartCode',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='mfgPartNo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='productCode',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='productName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='requestor',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='typeCode',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='description',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['cimcon_part_no'], name='items_itemm_cimcon__0d36fa_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['name'], name='items_itemm_name_51b93b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['main_category', 'sub_category'], name='items_itemm_main_ca_00a6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['make', 'product_model'], name='items_itemm_make_id_3cfee0_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['created_at'], name='items_itemm_created_fe4955_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['is_active'], name='items_itemm_is_acti_780019_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['mfg_part_no'], name='items_itemm_mfg_par_64aa51_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['status', 'created_at'], name='items_itemr_status_a70a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['requestor', 'status'], name='items_itemr_request_53cb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['cimcon_part_no'], name='items_itemr_cimcon__3433ed_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequest',
            index=models.Index(fields=['productCode', 'makeCode'], name='items_itemr_product_14a843_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['name'], name='items_mainc_name_c426c5_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['code'], name='items_mainc_code_ef472e_idx'),
        ),
        migrations.AddIndex(
            model_name='make',
            index=models.Index(fields=['main_category', 'code'], name='items_make_main_ca_10ecba_idx'),
        ),
        migrations.AddIndex(
            model_name='make',
            index=models.Index(fields=['name'], name='items_make_name_65fee6_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['main_category', 'code'], name='items_produ_main_ca_94ef7a_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['name'], name='items_produ_name_08c60e_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['main_category', 'code'], name='items_produ_main_ca_cb6892_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['sub_category', 'code'], name='items_produ_sub_cat_1f883c_idx'),
        ),
        migrations.AddIndex(
            model_name='remarks',
            index=models.Index(fields=['main_category', 'code'], name='items_remar_main_ca_9a1112_idx'),
        ),
        migrations.AddIndex(
            model_name='remarks',
            index=models.Index(fields=['description'], name='items_remar_descrip_10691c_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['main_category', 'code'], name='items_subca_main_ca_923378_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name'], name='items_subca_name_381041_idx'),
        ),
    ]
