# Generated by Django 4.2.17 on 2025-08-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemmaster_alternate_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='productrating',
            name='code',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AddField(
            model_name='factoryrating',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_ratings', to='items.maincategory'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='factory_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='items.factoryrating'),
        ),
        migrations.AddIndex(
            model_name='factoryrating',
            index=models.Index(fields=['main_category', 'code'], name='items_facto_main_ca_fdd69e_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryrating',
            index=models.Index(fields=['name'], name='items_facto_name_f963d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factoryrating',
            unique_together={('main_category', 'code')},
        ),
    ]
