# Generated by Django 4.2.17 on 2025-04-24 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indent_date', models.DateField()),
                ('ordering_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Partially Ordered', 'Partially Ordered'), ('Partially Delivered', 'Partially Delivered')], default='In Progress', max_length=20)),
                ('indent_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cimcon_part_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14}$', 'CIMCON Part Number must be exactly 14 alphanumeric characters.')])),
                ('mfg_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('material_description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('required_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('soh', models.IntegerField(blank=True, null=True)),
                ('balance_quantity', models.IntegerField(blank=True, null=True)),
                ('ordering_qty', models.IntegerField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(choices=[('SUP', 'Supply'), ('ITC', 'ITC'), ('ONM', 'O&M'), ('CON', 'Contract'), ('FRE', 'Freight'), ('SER', 'Service')], default='SUP', max_length=3, verbose_name='Order Type')),
                ('project_code', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='indent.requisition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
