# Generated by Django 4.2.17 on 2025-04-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(blank=True, max_length=150, null=True)),
                ('item_no', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=130, null=True)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('times_sq_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('i_sq_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sakar_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pirana_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inward_status', models.CharField(choices=[('open', 'Open'), ('partially_inwarded', 'Partially Inwarded'), ('completed', 'Completed')], default='open', max_length=20)),
                ('item_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('material_group', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('already_inwarded', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='indent.project')),
            ],
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_partial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('partially_outward', 'Partially Outward'), ('fully_outward', 'Fully Outward'), ('cancelled', 'Cancelled')], default='allocated', max_length=20)),
                ('reallocation_date', models.DateTimeField(blank=True, null=True)),
                ('reallocation_reason', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='store.inventory')),
                ('parent_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations', to='store.stockallocation')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_allocations', to='store.projectcode')),
            ],
        ),
        migrations.CreateModel(
            name='LocationWiseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('times_sq_stock', 'Times Square'), ('i_sq_stock', 'iSquare'), ('sakar_stock', 'Sakar'), ('pirana_stock', 'Pirana'), ('other_stock', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_allocations', to='store.stockallocation')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='inward_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='store.inwardentry'),
        ),
        migrations.CreateModel(
            name='StockOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('times_sq_stock', 'Times Square'), ('i_sq_stock', 'iSquare'), ('sakar_stock', 'Sakar'), ('pirana_stock', 'Pirana'), ('other_stock', 'Other')], db_index=True, max_length=50)),
                ('outward_type', models.CharField(choices=[('allocated', 'Allocated Stock'), ('available', 'Available Stock')], db_index=True, max_length=20)),
                ('document_type', models.CharField(choices=[('challan', 'Delivery Challan'), ('instructions', 'Billing Instructions')], max_length=20)),
                ('document_number', models.CharField(db_index=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('outward_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.projectcode')),
                ('stock_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outwards', to='store.stockallocation')),
            ],
            options={
                'ordering': ['-outward_date'],
                'indexes': [models.Index(fields=['outward_date', 'status'], name='store_stock_outward_de304b_idx'), models.Index(fields=['inventory', 'project_code'], name='store_stock_invento_5c916c_idx'), models.Index(fields=['document_type', 'document_number'], name='store_stock_documen_c3e9b5_idx')],
            },
        ),
    ]
