# Generated by Django 4.2.17 on 2025-05-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnableGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_number', models.CharField(max_length=20, unique=True)),
                ('pass_type', models.CharField(choices=[('outward', 'Outward - External'), ('internal', 'Internal Transfer')], max_length=20)),
                ('issue_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('issued_to', models.CharField(max_length=255)),
                ('issued_to_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.TextField()),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.projectcode')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnableGatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_location', models.CharField(max_length=50)),
                ('destination_location', models.CharField(blank=True, max_length=50, null=True)),
                ('condition_on_issue', models.TextField(blank=True, null=True)),
                ('condition_on_return', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.returnablegatepass')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnableGatePassReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.returnablegatepass')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnableGatePassReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gate_pass_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_entries', to='store.returnablegatepassitem')),
                ('gate_pass_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.returnablegatepassreturn')),
            ],
        ),
    ]
