# Generated by Django 4.2.17 on 2025-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_deliverychallan_rejectedmaterialreturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardentry',
            name='inward_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
