# Generated by Django 4.2.17 on 2025-11-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryItemDescription',
            fields=[
                ('itemdescid', models.AutoField(primary_key=True, serialize=False)),
                ('itemdesc', models.TextField()),
            ],
            options={
                'db_table': 'factory_itemdescriptions',
                'ordering': ['itemdescid'],
            },
        ),
        migrations.CreateModel(
            name='FactoryItemMaster',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('make_name', models.CharField(db_index=True, max_length=255)),
                ('mpn_full', models.CharField(db_index=True, max_length=255)),
                ('material_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('package_type', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.TextField()),
                ('full_part_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('moq', models.IntegerField(blank=True, default=0, null=True)),
                ('lead_time', models.IntegerField(blank=True, default=0, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bin_location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'factory_itemmaster',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryItemRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requestor', models.CharField(db_index=True, max_length=255)),
                ('productname', models.CharField(db_index=True, max_length=255)),
                ('productcode', models.CharField(db_index=True, max_length=255)),
                ('makename', models.CharField(db_index=True, max_length=255)),
                ('makecode', models.CharField(db_index=True, max_length=255)),
                ('mpnfull', models.CharField(db_index=True, max_length=255)),
                ('ratingvalue', models.CharField(blank=True, max_length=255, null=True)),
                ('packagecode', models.CharField(blank=True, max_length=255, null=True)),
                ('itemdesc', models.TextField()),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('moq', models.IntegerField(blank=True, default=0, null=True)),
                ('lead_time', models.IntegerField(blank=True, default=0, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bin_location', models.CharField(blank=True, max_length=50, null=True)),
                ('full_part_number', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'factory_itemrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryMake',
            fields=[
                ('makeid', models.AutoField(primary_key=True, serialize=False)),
                ('makename', models.CharField(db_index=True, max_length=255)),
                ('makecode', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'factory_makes',
                'ordering': ['makename'],
            },
        ),
        migrations.CreateModel(
            name='FactoryMPN',
            fields=[
                ('mpnid', models.AutoField(primary_key=True, serialize=False)),
                ('mpncode', models.CharField(db_index=True, max_length=255)),
                ('mpnfull', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'factory_mpns',
                'ordering': ['mpnfull'],
            },
        ),
        migrations.CreateModel(
            name='FactoryPackage',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('packagecode', models.CharField(db_index=True, max_length=255)),
                ('packagedesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factory_packages',
                'ordering': ['packagecode'],
            },
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(db_index=True, max_length=255)),
                ('productcode', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'factory_products',
                'ordering': ['productname'],
            },
        ),
        migrations.CreateModel(
            name='FactoryRating',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('ratingvalue', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='factory.factoryproduct')),
            ],
            options={
                'db_table': 'factory_ratings',
                'ordering': ['ratingvalue'],
            },
        ),
        migrations.AddIndex(
            model_name='factoryproduct',
            index=models.Index(fields=['productname'], name='factory_pro_product_aab83c_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryproduct',
            index=models.Index(fields=['productcode'], name='factory_pro_product_0b1d03_idx'),
        ),
        migrations.AddField(
            model_name='factorypackage',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='factorympn',
            name='makeid',
            field=models.ForeignKey(db_column='makeid', on_delete=django.db.models.deletion.CASCADE, related_name='mpns', to='factory.factorymake'),
        ),
        migrations.AddField(
            model_name='factorymake',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='factory.factoryproduct'),
        ),
        migrations.AddField(
            model_name='factoryitemrequest',
            name='makeid',
            field=models.ForeignKey(blank=True, db_column='makeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='factory.factorymake'),
        ),
        migrations.AddField(
            model_name='factoryitemrequest',
            name='productid',
            field=models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='factory.factoryproduct'),
        ),
        migrations.AddIndex(
            model_name='factoryitemmaster',
            index=models.Index(fields=['product_name'], name='factory_ite_product_ead444_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemmaster',
            index=models.Index(fields=['make_name'], name='factory_ite_make_na_69d743_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemmaster',
            index=models.Index(fields=['full_part_number'], name='factory_ite_full_pa_4a5654_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemmaster',
            index=models.Index(fields=['created_at'], name='factory_ite_created_408b4f_idx'),
        ),
        migrations.AddField(
            model_name='factoryitemdescription',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, related_name='item_descriptions', to='factory.factoryproduct'),
        ),
        migrations.AddIndex(
            model_name='factoryrating',
            index=models.Index(fields=['productid', 'ratingvalue'], name='factory_rat_product_d47781_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryrating',
            index=models.Index(fields=['ratingvalue'], name='factory_rat_ratingv_9bed98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factoryrating',
            unique_together={('productid', 'ratingvalue')},
        ),
        migrations.AddIndex(
            model_name='factorypackage',
            index=models.Index(fields=['productid', 'packagecode'], name='factory_pac_product_7bc9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='factorypackage',
            index=models.Index(fields=['packagecode'], name='factory_pac_package_9c243a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factorypackage',
            unique_together={('productid', 'packagecode')},
        ),
        migrations.AddIndex(
            model_name='factorympn',
            index=models.Index(fields=['makeid', 'mpncode'], name='factory_mpn_makeid_ad3a63_idx'),
        ),
        migrations.AddIndex(
            model_name='factorympn',
            index=models.Index(fields=['mpncode'], name='factory_mpn_mpncode_17f70e_idx'),
        ),
        migrations.AddIndex(
            model_name='factorympn',
            index=models.Index(fields=['mpnfull'], name='factory_mpn_mpnfull_ae2429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factorympn',
            unique_together={('makeid', 'mpncode')},
        ),
        migrations.AddIndex(
            model_name='factorymake',
            index=models.Index(fields=['productid', 'makecode'], name='factory_mak_product_d947c7_idx'),
        ),
        migrations.AddIndex(
            model_name='factorymake',
            index=models.Index(fields=['makename'], name='factory_mak_makenam_dd816e_idx'),
        ),
        migrations.AddIndex(
            model_name='factorymake',
            index=models.Index(fields=['makecode'], name='factory_mak_makecod_7ab5a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factorymake',
            unique_together={('productid', 'makecode')},
        ),
        migrations.AddIndex(
            model_name='factoryitemrequest',
            index=models.Index(fields=['status', 'created_at'], name='factory_ite_status_8f2231_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemrequest',
            index=models.Index(fields=['requestor', 'status'], name='factory_ite_request_db2111_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemrequest',
            index=models.Index(fields=['full_part_number'], name='factory_ite_full_pa_da312e_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemrequest',
            index=models.Index(fields=['productcode', 'makecode'], name='factory_ite_product_3c532e_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryitemdescription',
            index=models.Index(fields=['productid'], name='factory_ite_product_e6153b_idx'),
        ),
    ]
