# Generated by Django 4.2.17 on 2025-11-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factorymake',
            unique_together={('productid', 'makecode'), ('productid', 'makename')},
        ),
    ]
