# Generated by Django 4.2.17 on 2025-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_add_unique_make_name_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryitemrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoryitemrequest',
            name='mpncode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factoryitemrequest',
            name='packagedesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
