# Generated by Django 4.2.17 on 2025-04-24 11:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('client_project_name', models.CharField(max_length=255)),
                ('bill_to', models.TextField(blank=True, null=True)),
                ('ship_to', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=255)),
                ('submitted_by', models.CharField(max_length=255)),
                ('requested_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('item_no', models.PositiveIntegerField(blank=True, null=True)),
                ('cimcon_part_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14}$', 'CIMCON Part Number must be exactly 14 alphanumeric characters.')])),
                ('mfg_part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('material_description', models.TextField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('req_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_status', models.BooleanField(default=False)),
                ('verification_status', models.BooleanField(default=False)),
                ('master_entry_exists', models.BooleanField(default=False)),
                ('requisition_date', models.DateField(default=datetime.date)),
                ('submitted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_remarks', models.TextField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('SUP', 'Supply'), ('ITC', 'ITC'), ('O&M', 'Onm'), ('CON', 'Contract'), ('FRE', 'Freight'), ('SER', 'Service')], default='SUP', max_length=3, verbose_name='Order Type')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='indent.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('revision_number', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indent.requisition')),
            ],
        ),
    ]
