# Generated by Django 4.2.17 on 2025-04-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('indent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.division'),
        ),
    ]
