# Generated by Django 4.2.17 on 2025-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='order_type',
            field=models.CharField(choices=[('SUP', 'Supply'), ('ITC', 'ITC'), ('ONM', 'O&M'), ('CON', 'Contract'), ('FRE', 'Freight'), ('SER', 'Service')], default='SUP', max_length=3, verbose_name='Order Type'),
        ),
    ]
