# Generated by Django 4.2.17 on 2025-06-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0006_alter_requisition_cimcon_part_number'),
        ('indent', '0007_add_performance_indexes'),
    ]

    operations = [
    ]
