# Generated by Django 4.2.17 on 2025-06-03 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0008_merge_20250603_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_project_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approved_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='batch_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cimcon_part_number',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14,}$', 'CIMCON Part Number must be greater than or equal to 14 and less than or equal to 17 alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='requisitionhistory',
            name='field_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code', 'division'], name='indent_proj_project_b595f3_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['batch_id', 'status'], name='indent_requ_batch_i_44b518_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['project', 'approved_status'], name='indent_requ_project_25e65d_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['cimcon_part_number', 'status'], name='indent_requ_cimcon__a7a664_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionhistory',
            index=models.Index(fields=['requisition', 'field_name'], name='indent_requ_requisi_1efe15_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitionhistory',
            index=models.Index(fields=['changed_at', 'field_name'], name='indent_requ_changed_b8be7a_idx'),
        ),
    ]
