# Generated by Django 4.2.17 on 2025-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchaseorder_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polineitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
