# Generated by Django 4.2.17 on 2025-09-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_polineitem_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohistory',
            name='new_version',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='pohistory',
            name='previous_version',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
