# Generated by Django 4.2.17 on 2025-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_pohistory_new_version_pohistory_previous_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polineitem',
            name='added_in_revision',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Version number when this item was added to the PO', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='Whether this item was modified in a revision'),
        ),
    ]
