# Generated by Django 4.2.17 on 2025-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0010_purchaseorder_is_revised'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_number',
            field=models.IntegerField(default=1, help_text='Revision number for this PO'),
        ),
    ]
