# Generated by Django 4.2.17 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0011_purchaseorder_revision_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="po_type",
            field=models.CharField(
                choices=[("domestic", "Domestic"), ("overseas", "Overseas")],
                default="domestic",
                max_length=20,
            ),
        ),
    ]
