# Generated by Django 4.2.17 on 2025-05-26 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='cimcon_part_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14,17}$', 'CIMCON Part Number must be between 14 and 17 alphanumeric characters.')]),
        ),
    ]
