# Generated by Django 4.2.17 on 2025-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_master_cimcon_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
