# Generated by Django 4.2.17 on 2025-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_returnablegatepass_returnablegatepassitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnablegatepass',
            name='document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
