# Generated by Django 4.2.17 on 2025-05-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_returnablegatepass_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch_from', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_to', models.TextField(blank=True, null=True)),
                ('ship_to', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.projectcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectedMaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=200)),
                ('return_date', models.DateField()),
                ('reason_for_return', models.TextField()),
                ('action_taken', models.CharField(choices=[('pending', 'Pending Processing'), ('added_to_stock', 'Added to Stock'), ('discarded', 'Discarded/Scrapped')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.projectcode')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, choices=[('times_sq_stock', 'Times Square'), ('i_sq_stock', 'iSquare'), ('sakar_stock', 'Sakar'), ('pirana_stock', 'Pirana'), ('other_stock', 'Other')], max_length=50, null=True)),
                ('condition', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('add_to_stock', 'Add to Stock'), ('discard', 'Discard/Scrap')], max_length=20)),
                ('reason_details', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
                ('material_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.rejectedmaterialreturn')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=130, null=True)),
                ('material_group', models.CharField(blank=True, max_length=150, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(default='NOS', max_length=20)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.deliverychallan')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
            ],
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['document_number'], name='store_deliv_documen_342dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['date'], name='store_deliv_date_b62717_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['project_code'], name='store_deliv_project_2fc6fc_idx'),
        ),
    ]
