# Generated by Django 4.2.17 on 2025-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_inwardentry_inward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='document_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='item_no',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='allocated_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_no',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='make',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='material_group',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='inward_status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], db_index=True, default='Ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='item_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='make',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='material_group',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='po_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inwardentry',
            name='received_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='locationwiseallocation',
            name='location',
            field=models.CharField(choices=[('times_sq_stock', 'Times Square'), ('i_sq_stock', 'iSquare'), ('sakar_stock', 'Sakar'), ('pirana_stock', 'Pirana'), ('other_stock', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='locationwiseallocation',
            name='quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialitem',
            name='action',
            field=models.CharField(choices=[('add_to_stock', 'Add to Stock'), ('discard', 'Discard/Scrap')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialreturn',
            name='action_taken',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('added_to_stock', 'Added to Stock'), ('discarded', 'Discarded/Scrapped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialreturn',
            name='challan_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialreturn',
            name='client_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rejectedmaterialreturn',
            name='return_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='expected_return_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='gate_pass_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='issued_to',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='pass_type',
            field=models.CharField(choices=[('outward', 'Outward - External'), ('internal', 'Internal Transfer')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='source_location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='returnablegatepass',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('partially_returned', 'Partially Returned'), ('fully_returned', 'Fully Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnablegatepassitem',
            name='source_location',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='returnablegatepassreturn',
            name='return_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='allocated_quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='allocation_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='is_partial',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stockallocation',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('partially_outward', 'Partially Outward'), ('fully_outward', 'Fully Outward'), ('cancelled', 'Cancelled')], db_index=True, default='allocated', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockoutward',
            name='document_type',
            field=models.CharField(choices=[('challan', 'Delivery Challan'), ('instructions', 'Billing Instructions')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['created_at'], name='store_deliv_created_b4d556_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item_no'], name='store_inven_item_no_b5259c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['material_group'], name='store_inven_materia_72a90a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['make'], name='store_inven_make_293c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['total_stock', 'available_stock'], name='store_inven_total_s_239e25_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item_no', 'material_group'], name='store_inven_item_no_8d0d07_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['po_number', 'item_code'], name='store_inwar_po_numb_ebc31d_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['received_date', 'inward_status'], name='store_inwar_receive_107f94_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['location', 'received_date'], name='store_inwar_locatio_d44a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='locationwiseallocation',
            index=models.Index(fields=['stock_allocation', 'location'], name='store_locat_stock_a_00f73b_idx'),
        ),
        migrations.AddIndex(
            model_name='locationwiseallocation',
            index=models.Index(fields=['location', 'quantity'], name='store_locat_locatio_fc2651_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['name'], name='store_proje_name_fa0fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcode',
            index=models.Index(fields=['code'], name='store_proje_code_id_c05121_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['inventory', 'status'], name='store_stock_invento_1137bb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['project_code', 'status'], name='store_stock_project_0ad507_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['allocation_date', 'status'], name='store_stock_allocat_658e63_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['inventory', 'project_code'], name='store_stock_invento_f221cf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoutward',
            index=models.Index(fields=['inventory', 'outward_date'], name='store_stock_invento_893d75_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoutward',
            index=models.Index(fields=['project_code', 'outward_date'], name='store_stock_project_ea9b3e_idx'),
        ),
    ]
