# Generated by Django 4.2.17 on 2025-06-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_deliverychallan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardentry',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inwardentry',
            name='purchase_invoice',
            field=models.FileField(blank=True, null=True, upload_to='purchase_invoices/'),
        ),
        migrations.AddIndex(
            model_name='inwardentry',
            index=models.Index(fields=['invoice_number', 'invoice_date'], name='store_inwar_invoice_0f13f7_idx'),
        ),
    ]
