# Generated by Django 4.2.17 on 2025-05-23 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0003_alter_requisition_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='cimcon_part_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{14}$', 'CIMCON Part Number must be exactly 17 alphanumeric characters.')]),
        ),
    ]
