# Generated by Django 4.2.17 on 2025-05-26 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0004_alter_requisition_cimcon_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='cimcon_part_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{15,17}$', 'CIMCON Part Number must be greater than 15 and less than or equal to 17 alphanumeric characters.')]),
        ),
    ]
