# Generated by Django 4.2.17 on 2025-04-24 11:09

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('productName', models.CharField(max_length=255)),
                ('productCode', models.CharField(max_length=3)),
                ('mfgPartNo', models.CharField(max_length=255)),
                ('mfgPartCode', models.CharField(max_length=3)),
                ('itemDescription', models.TextField()),
                ('itemCode', models.CharField(max_length=3)),
                ('make', models.CharField(max_length=100)),
                ('makeCode', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=100)),
                ('typeCode', models.CharField(max_length=2)),
                ('materialRating', models.CharField(blank=True, max_length=100, null=True)),
                ('materialRatingCode', models.CharField(blank=True, max_length=3, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('moq', models.IntegerField(blank=True, null=True)),
                ('leadTime', models.IntegerField(blank=True, null=True)),
                ('hsnCode', models.CharField(blank=True, max_length=50, null=True)),
                ('bin', models.CharField(blank=True, max_length=50, null=True)),
                ('cimcon_part_no', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to=items.models.item_file_path)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='items.maincategory')),
            ],
            options={
                'unique_together': {('main_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='items.maincategory')),
            ],
            options={
                'unique_together': {('main_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='items.maincategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='items.subcategory')),
            ],
            options={
                'unique_together': {('main_category', 'sub_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='items.maincategory')),
            ],
            options={
                'unique_together': {('main_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=2)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='items.maincategory')),
            ],
            options={
                'unique_together': {('main_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cimcon_part_no', models.CharField(max_length=16, unique=True)),
                ('alternate_no', models.CharField(blank=True, max_length=16, null=True)),
                ('mfg_part_no', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('uom', models.CharField(blank=True, max_length=255, null=True)),
                ('moq', models.IntegerField(blank=True, null=True)),
                ('mfg_std_lead_time', models.IntegerField(blank=True, null=True)),
                ('bin', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to=items.models.item_file_path)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.maincategory')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.make')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.productmodel')),
                ('product_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.productrating')),
                ('remarks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.remarks')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.subcategory')),
            ],
        ),
    ]
