# Generated by Django 4.2.17 on 2025-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemmaster_alternate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
