# Generated by Django 4.2.17 on 2025-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_productrating_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
