# Generated by Django 4.2.17 on 2025-09-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_fix_remarks_constraints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remarks',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='cimcon_part_no',
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='itemCode',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
