# Generated by Django 4.2.17 on 2025-11-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_create_factory_rating_model'),
        ('items', '0006_alter_remarks_unique_together_and_more'),
    ]

    operations = [
    ]
