# Generated by Django 4.2.17 on 2025-11-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_merge_20251105_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='factory_rating',
        ),
        migrations.AlterField(
            model_name='productrating',
            name='code',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.DeleteModel(
            name='FactoryRating',
        ),
    ]
