# Generated by Django 4.2.17 on 2025-04-24 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PONumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=4, unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'po_number_sequence',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('quote_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField()),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.TextField(default='100% Against Invoice')),
                ('warranty_terms', models.TextField(default='1 year from date of invoice')),
                ('delivery_schedule', models.TextField(default='1 week from date of Purchase order')),
                ('dispatch_terms', models.TextField(default='Freight & Insurance Extra')),
                ('tpi_terms', models.TextField(default='TPI Inspection Exclusive')),
                ('installation_terms', models.TextField(default='Installation Exclusive')),
                ('commissioning', models.TextField(default='Commissioning Exclusive')),
                ('vendor_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_payment_terms', models.TextField(blank=True, null=True)),
                ('consignee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('consignee_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('consignee_attention', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('invoice_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('partially_ordered', 'Partially Ordered'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='NA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('inward_status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('partially_ordered', 'Partially Ordered'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('total_inwarded_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approval_status', models.BooleanField(default=False)),
                ('rejection_status', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_remarks', models.TextField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.IntegerField()),
                ('item_no', models.CharField(max_length=100)),
                ('material_description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('inwarded_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_order.purchaseorder')),
            ],
            options={
                'db_table': 'po_line_items',
            },
        ),
        migrations.CreateModel(
            name='POHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase_order.purchaseorder')),
            ],
            options={
                'db_table': 'po_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
