# Generated by Django 4.2.17 on 2025-04-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorder_vendor_pan_purchaseorder_vendor_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='dispatch_terms',
            new_name='freight_terms',
        ),
    ]
