# Generated by Django 4.2.17 on 2025-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_rename_dispatch_terms_purchaseorder_freight_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
