# Generated by Django 4.2.17 on 2025-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
