# Generated by Django 4.2.17 on 2025-10-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_polineitem_added_in_revision_polineitem_is_revised'),
    ]

    operations = [
    ]
