# Generated by Django 4.2.17 on 2025-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_fake_is_revised'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_revised',
            field=models.BooleanField(default=False, help_text='Whether this PO has been revised'),
        ),
    ]
